# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-04 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
    ]
