# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20181204_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[profiles.validators.validate_city]),
        ),
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[profiles.validators.validate_country]),
        ),
        migrations.AlterField(
            model_name='users',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[profiles.validators.validate_state]),
        ),
    ]
