# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-04 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
